### ISSUE TITLE
app_agent_receiver_configs in config file causing start Grafana Agent failed

### ISSUE THREAD

**Issue by Humbertzhang** [grafana/faro-web-sdk#103]
## Description

Hello, I'm new to grafana and faro-web-sdk, and I'm following your quick-start document.
However, I'm facing some problems when I try to set up my grafana agent, and i'm following 
the config file from [quick-start-browser.md](https://github.com/grafana/faro-web-sdk/blob/main/docs/sources/tutorials/quick-start-browser.md#before-you-begin) to start it. 

When I start it, it says:

```
/usr/bin/grafana-agent --config.file /etc/grafana-agent.yaml 
2023/01/28 15:19:32 error loading config file /etc/grafana-agent.yaml: yaml: unmarshal errors:
  line 1: field app_agent_receiver_configs not found in type integrations.ManagerConfig
```

According to my knowledge, the `app_agent_receiver_configs` is a config for faro, 
and I don't know why it caused the grafana agent can't start.

## Steps to reproduce

I’m using the prometheus, loki and tempo address provided by Grafana Cloud, 
and my config is：
```yaml
metrics:
  wal_directory: /tmp/wal
  global: {}
  configs:
    - name: default
      remote_write:
        - url: https://prometheus-prod-xx-prod-ap-southeast-0.grafana.net/api/prom/push
          basic_auth:
            username: <myUserName>
            password: <myAPIKEY>
logs:
  positions_directory: /tmp/loki-pos
  configs:
    - name: default
      scrape_configs: []
      clients:
        - url: https://<myUserName>:<myAPIKEY>@logs-prod-xxx.grafana.net/loki/api/v1/push
traces:
  configs:
    - name: default
      remote_write:
        - endpoint: tempo-prod-xx-prod-ap-southeast-x.grafana.net:xxx
          basic_auth:
            username: <myUserName>
            password: <myAPIKEY>
      receivers:
        otlp:
          protocols:
            grpc:
            http:
              cors:
                allowed_origins:
                  - http://localhost:1234
                max_age: 7200
integrations:
  app_agent_receiver_configs:
    - autoscrape:
        enable: true
        metrics_instance: 'default'
      #api_key: 'secret' # optional, if set, client will be required to provide it via x-api-key header
      instance: 'frontend'
      logs_instance: 'default'
      traces_instance: 'default'
      server:
        host: 0.0.0.0
        port: 9090
        cors_allowed_origins:
          - 'https://my-app.example.com'
      logs_labels: # labels to add to loki log record
        app: frontend # static value
        kind: # value will be taken from log items. exception, log, measurement, etc
      logs_send_timeout: 5000
      sourcemaps:
        download: true # will download source file, extract source map location,
        # download source map and use it to transform stack trace locations
```

## Expected behavior
start grafana agent success

## Actual behavior
start grafana agent failed

## Environment

**OS: CentOS 7**

**Grafana Agent:** 
```
/usr/bin/grafana-agent -version 
agent, version v0.30.2 (branch: HEAD, revision: 59144c61)
  build user:       root@c01bcc4cd472
  build date:       2023-01-11T17:46:30Z
  go version:       go1.19.3
  platform:         linux/amd64
```
