### ISSUE TITLE
Traces have wrong Trace Start time

### ISSUE THREAD

**Issue by mjovanovic0** [grafana/faro-web-sdk#81]
## Description

After the setup of the LGTM stack with Faro and Grafana Agent receiver, and configuring React app the same way as it is a demo application, tracers are received and able to browse them in Tempo but they all have the wrong Trace Start time.
Logs on the other hand in Loki have the correct time.

![trace](https://user-images.githubusercontent.com/6703229/207846362-bb2200c4-dd43-4b9c-b5cf-0d9f6e58cc4f.png)

Agent configuration:
```yaml
metrics:
  wal_directory: /tmp/wal
  global: {}
  configs:
    - name: default
      remote_write:
        - url: http://prometheus.app:9090/api/v1/write
logs:
  positions_directory: /tmp/loki-pos
  configs:
    - name: default
      clients:
        - url: http://loki..app:3100/loki/api/v1/push
      scrape_configs:
      - job_name: frontend-core-ui
        pipeline_stages:
          - logfmt:
              mapping:
                timestamp: timestamp
          - timestamp:
              format: "2006-01-02 15:04:05.000 -0700 MST"
              source: timestamp
          - output:
              source: output
        static_configs:
          - labels:
              job: frontend-core-ui

traces:
  configs:
    - name: default
      remote_write:
        - endpoint: tempo.app:4317
          insecure: true
          tls_config:
            insecure_skip_verify: true
      receivers:
        otlp:
          protocols:
            grpc:
            http:
              cors:
                allowed_origins:
                  - http://localhost:8080
                max_age: 7200

integrations:
  app_agent_receiver_configs:
    - autoscrape:
        enable: true
        metrics_instance: 'default'
      instance: 'frontend-core-ui'
      logs_instance: 'default'
      traces_instance: 'default'
      server:
        host: 0.0.0.0
        port: 8081
        cors_allowed_origins:
          - 'http://localhost:3000'
      logs_labels: # labels to add to loki log record
        job: frontend-core-ui
        kind: # value will be taken from log items. exception, log, measurement, etc
        Time:
        timestamp:
      logs_send_timeout: 5000
      sourcemaps:
        download: true
```

Don't know where to look anymore for potential fix...

## Environment

- **SDK version:** 1.0.0-beta3
- **SDK instrumentations:** Core, Web SDK, Web Tracing, React
- **Device type:** desktop
- **Device name:** MacBook Pro 16"
- **OS:** macOS Ventura 13.1
- **Browser:** Chrome 108.0.5359.98
